"""
Summary Agent — aggregates findings from all specialist agents and:
  1. De-duplicates overlapping findings
  2. Computes an overall quality score (0–10)
  3. Determines if the PR should be blocked (CRITICAL security finding)
  4. Renders a structured Markdown comment for GitHub
"""

from __future__ import annotations

import json
import re
import time
from datetime import datetime, timezone

from langchain_core.messages import HumanMessage, SystemMessage

from src.tools.dynamo_memory import DynamoMemoryStore

DEDUP_PROMPT = """You are reviewing three sets of findings from separate code review agents.
Remove genuine duplicates (same file, same issue, similar recommendation).
Keep the most detailed version of each unique finding.
Return a merged JSON array using the same schema as the input.
Do NOT include any text outside the JSON array.
"""


def severity_emoji(severity: str) -> str:
    return {
        "CRITICAL": "🔴",
        "HIGH": "🟠",
        "MEDIUM": "🟡",
        "LOW": "🔵",
        "INFO": "ℹ️",
    }.get(severity.upper(), "⚪")


SEVERITY_WEIGHTS: dict[str, float] = {"CRITICAL": 3.0, "HIGH": 1.5, "MEDIUM": 0.5, "LOW": 0.1}


def compute_score_breakdown(findings: list[dict]) -> dict:
    """Return the per-severity breakdown that drives the final score."""
    non_pos = [f for f in findings if f.get("category") != "positive"]
    pos_count = sum(1 for f in findings if f.get("category") == "positive")
    counts = {
        sev: sum(1 for f in non_pos if f.get("severity", "").upper() == sev)
        for sev in SEVERITY_WEIGHTS
    }
    deductions = {sev: round(counts[sev] * SEVERITY_WEIGHTS[sev], 1) for sev in counts}
    total_deduction = round(sum(deductions.values()), 1)
    pos_boost = round(pos_count * 0.1, 1)
    raw = round(10.0 - total_deduction + pos_boost, 1)
    return {
        "severity_counts": counts,
        "severity_weights": SEVERITY_WEIGHTS,
        "severity_deductions": deductions,
        "total_deduction": total_deduction,
        "positive_count": pos_count,
        "positive_boost": pos_boost,
        "raw_score": raw,
        "final_score": max(0.0, min(10.0, raw)),
    }


def compute_score(findings: list[dict]) -> float:
    """Deduct points from 10 based on severity counts."""
    return compute_score_breakdown(findings)["final_score"]


def render_github_comment(
    pr_meta: dict,
    all_findings: list[dict],
    score: float,
    should_block: bool,
) -> str:
    """Render the full Markdown comment to post on the PR."""
    ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Group by severity
    by_severity: dict[str, list[dict]] = {}
    for f in all_findings:
        sev = f.get("severity", "INFO").upper()
        by_severity.setdefault(sev, []).append(f)

    lines = [
        "## 🤖 AI PR Review",
        f"> Generated by **PR Review System** · {ts}",
        "",
        "---",
        "",
        f"### Overall score: **{score}/10**",
    ]

    if should_block:
        lines += [
            "",
            "> [!CAUTION]",
            "> **BLOCKED** — Critical security finding detected. This PR must not be merged until resolved.",
        ]
    elif score >= 8:
        lines.append("> ✅ Looks good to merge after addressing the items below.")
    elif score >= 5:
        lines.append("> ⚠️ Needs some work before merging.")
    else:
        lines.append("> ❌ Significant issues found — please address before merging.")

    # Summary table
    lines += ["", "### Finding summary", ""]
    lines.append("| Severity | Count |")
    lines.append("|---|---|")
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"]:
        count = len(by_severity.get(sev, []))
        if count:
            lines.append(f"| {severity_emoji(sev)} {sev} | {count} |")

    # Detail sections
    for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
        items = [f for f in by_severity.get(sev, []) if f.get("category") != "positive"]
        if not items:
            continue
        lines += ["", f"### {severity_emoji(sev)} {sev}", ""]
        for item in items:
            loc = f"`{item.get('file', 'general')}`" + (
                f" line {item['line']}" if item.get("line") else ""
            )
            lines.append(f"**{item.get('title', 'Finding')}** — {loc}")
            lines.append(f"> {item.get('detail', '')}")
            if item.get("recommendation"):
                lines.append(f"> 💡 **Recommendation:** {item['recommendation']}")
            if item.get("code_suggestion"):
                lines.append(f"\n```\n{item['code_suggestion']}\n```")
            lines.append("")

    # Positives
    positives = [f for f in all_findings if f.get("category") == "positive"]
    if positives:
        lines += ["", "### ✅ Things done well", ""]
        for p in positives:
            lines.append(
                f"- **{p.get('title', '').lstrip('✓ ')}**: {p.get('detail', '')}"
            )

        lines += [
            "",
            "---",
            "<sub>Powered by LangGraph · AWS Bedrock Claude Haiku · Anthropic</sub>",
        ]
    return "\n".join(lines)


class SummaryAgent:
    def __init__(self, llm, memory_store: DynamoMemoryStore):
        self.llm = llm
        self.memory = memory_store

    def run(self, state: dict) -> dict:
        started_at = datetime.now(tz=timezone.utc).isoformat()
        t0 = time.monotonic()

        pr_meta = state["pr_metadata"]
        thread_id = pr_meta.get("thread_id") or f"pr-{pr_meta['repo']}-{pr_meta['number']}"

        security_findings = state.get("security_findings", [])
        code_quality_findings = state.get("code_quality_findings", [])
        pr_review_findings = state.get("pr_review_findings", [])

        all_raw = security_findings + code_quality_findings + pr_review_findings

        # LLM-based deduplication
        if all_raw:
            messages = [
                SystemMessage(content=DEDUP_PROMPT),
                HumanMessage(content=json.dumps(all_raw, indent=2)[:12000]),
            ]
            response = self.llm.invoke(messages)
            try:
                raw = response.content.strip()
                if raw.startswith("```"):
                    raw = re.sub(r"^```[a-z]*\n?", "", raw)
                    raw = re.sub(r"\n?```$", "", raw)
                all_findings = json.loads(raw)
            except Exception:
                all_findings = all_raw
        else:
            all_findings = []

        should_block = state.get("should_block", False) or any(
            f.get("severity") == "CRITICAL" for f in all_findings
        )
        breakdown = compute_score_breakdown(all_findings)
        score = breakdown["final_score"]
        comment = render_github_comment(pr_meta, all_findings, score, should_block)

        # Persist to shared memory
        self.memory.put(thread_id, "summary_report", comment)
        self.memory.put(thread_id, "overall_score", str(score))
        self.memory.put(thread_id, "score_breakdown", json.dumps(breakdown))

        # Record lineage
        self.memory.put(thread_id, "lineage_summary", json.dumps({
            "agent": "summary",
            "started_at": started_at,
            "completed_at": datetime.now(tz=timezone.utc).isoformat(),
            "duration_ms": int((time.monotonic() - t0) * 1000),
            "reads_from": ["security_findings", "code_quality_findings", "pr_review_findings"],
            "writes_to": ["summary_report", "overall_score"],
            "input_summary": {
                "security_count": len(security_findings),
                "code_quality_count": len(code_quality_findings),
                "pr_review_count": len(pr_review_findings),
                "total_raw": len(all_raw),
            },
            "output_summary": {
                "final_findings": len(all_findings),
                "duplicates_removed": max(0, len(all_raw) - len(all_findings)),
                "score": score,
                "should_block": should_block,
            },
        }))

        completed = list(state.get("completed_agents", []))
        if "summary" not in completed:
            completed.append("summary")

        return {
            "summary_report": comment,
            "overall_score": score,
            "should_block": should_block,
            "score_breakdown": breakdown,
            "completed_agents": completed,
        }
